version: 2
updates:
  - package-ecosystem: cargo
    directory: /core
    schedule:
      interval: weekly
    labels:
      - dependencies
    commit-message:
      prefix: chore
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    commit-message:
      prefix: chore
    open-pull-requests-limit: 5
